urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login/?$', 'web.views.account.login', name='login'),
    url(r'^logout/?$', 'web.views.account.logout', name='logout'),
    url(r'^register/?$', 'web.views.account.register', name='register'),
    url(r'^validate/$', 'web.views.account.validate', name='validate'),
    url(r'^forgot_password/?$', 'web.views.account.forgot_password', name='forgot_password'),
    url(r'^account/?$', 'web.views.account.index', name='account'),

    url(r'^batch_add/?$', 'web.views.admin.batch_add', name='batch_add'),
    url(r'^view_videos/?$', 'web.views.admin.list_videos', name='list_videos'),

    url(r'^ajax/vote/(\d+)/(\d+)/(\d+)/?$', 'web.views.ajax.vote', name='vote'),

    url(r'^submit/(\d+)?/?$', 'web.views.submission.index', name='submit'),

    url(r'^post/(\d+)/?$', 'web.views.home.post', name='post'),
    url(r'^category/(\d+)/?$', 'web.views.home.category', name='category'),
    url(r'^expos/(\d+)/?$', 'web.views.home.expos', name='expos'),
    url(r'^$', 'web.views.home.index', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^mu-25b8a55c-a9fee579-723dcc44-9782bfc2$', 'web.views.blitz.index'),
    url(r'^google3da26e317e8e8cda.html$', 'web.views.google_webmaster.index'),
)

web/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)
    prereq = models.ManyToManyField("self", blank=True, symmetrical=False, related_name="postreq")
    parent = models.ManyToManyField("self", blank=True, symmetrical=False, related_name="child")

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.name

class Exposition(models.Model):
    title = models.CharField(max_length=100) # title of the article or website
    link = models.CharField(max_length=100) # A URL to the location of the exposition
    cat = models.ForeignKey(Category)

    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return self.title

class Submission(models.Model):
    owner = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True, blank=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    video = models.CharField(max_length=400, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, default=datetime.now)
    date_modified = models.DateTimeField(auto_now=True, default=datetime.now)
    tags = models.ManyToManyField(Category)

    def __unicode__(self):
        return self.title

class VoteCategory(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Vote categories"

    def __unicode__(self):
        return self.name

class Vote(models.Model):
    user = models.ForeignKey(User)
    submission = models.ForeignKey(Submission, related_name='votes')
    v_category = models.ForeignKey(VoteCategory, related_name='votes')
    rating = models.IntegerField()
    date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '%s: %s: %s' % (self.user, self.submission.title, self.v_category.name)

web/templates/base.html
<!doctype html>
<html lang="en">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title|default:"KnoAtom" }}</title>
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery.min.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/swfobject.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/wysihtml5-0.3.0_rc2.min.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/bootstrap-wysihtml5.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/bootstrap-modal.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/bootstrap-button.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/bootstrap-dropdown.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/bootstrap-tab.js"></script>
<script type="text/javascript" src="{{ STATIC_PREFIX }}js/knoatom.js"></script>
<link href="{{ STATIC_PREFIX }}css/bootstrap.min.css" rel="stylesheet">
<link href="{{ STATIC_PREFIX }}css/bootstrap-responsive.css" rel="stylesheet">
<link href="{{ STATIC_PREFIX }}css/bootstrap-wysihtml5.css" rel="stylesheet">
{% block head %}
{% endblock %}
</head>
<body>

<div class="container">

<div class="row">
<div class="span12">
<ul class="breadcrumb">
<li>
<a href="/">KnoAtom</a> |
</li>
{% for b in breadcrumbs %}
<li class="{% if forloop.last %}active{% endif %}">
<a href="{{ b.url }}">{{ b.title }}</a>
{% if not forloop.last %}<span class="divider">/</span>{% endif %}
</li>
{% endfor %}
</ul>
</div> <!-- end .span12 -->
</div> <!-- end .row -->

<div class="row">
<div class="span3">
<div class="well">
{% block navigation %}
<ul class="nav nav-list" style="padding-left:0;padding-right:0;">
<li class="nav-header">Categories</li>
{% for c in parent_categories %}
<li class="divider"></li>
<li class="{% if c.id == parent_category.id %}open{% endif %} {% if c.id == selected_category.id %}active{% endif %}">
<a href="{% url category c.id %}"><i class="sidebar-dropdown-toggle icon-minus"></i> {{ c }}</a>
<ul class="nav nav-list">
{% for sc in c.child.all %}
<li class="{% if sc.id == selected_category.id %}active{% endif %}">
<a href="{% url category sc.id%}">{{ sc }}</a>
</li>
{% endfor %}
</ul>
</li>
{% endfor %}
<!-- meta -->
<li class="divider"></li>
<li class="nav-header">Meta</li>
{% if user.is_authenticated %}
<li><a href="{% url account %}">{{ user }}</a></li>
<li><a href="{% url submit %}">Submit New Content</a></li>
<li><a href="{% url logout %}">Logout</a></li>
{% else %}
<li><a href="{% url login %}">Login</a></li>
<li><a href="{% url register %}">Register</a></li>
{% endif %}
</ul>
{% endblock %}
</div> <!-- end .well -->
</div> <!-- end .span3 -->
<div class="span9">
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endfor %}
{% block content %}
{% endblock %}
</div> <!-- end .span9 -->
</div> <!-- end .row -->

<div class="row">
<div class="span12">
<div id="footer">
<p>Copyright &copy; 2012</p>
</div> <!-- end #footer -->
</div> <!-- end .span12 -->
</div> <!-- end .row -->
</div> <!-- end .container -->

<div class="modal fade" id="global_modal" >
<div class="modal-header">
<a class="close" data-dismiss="modal">x</a><h3>Video Preview</h3>
</div>
<div class="modal-body">
<!-- empty, for now -->
</div>
</div> <!-- end #global_modal -->

<div class="modal fade" id="expo_modal" >
<div class="modal-header">
<a class="close" data-dismiss="modal">x</a><h3>Exposition viewer</h3>
</div>
<div class="modal-body">
<!-- empty, for now -->
</div>
</div> <!-- end #expo_modal -->

<script type="text/javascript" src="{{ STATIC_PREFIX }}js/analytics.js"></script>
</body>
</html>

web/templates/form_template.html
{% if form.non_field_errors %}
<div class="alert alert-warning">{{ form.non_field_errors }}</div>
{% endif %}
{% for field in form.hidden_fields %}
{{ field }}
{% endfor %}
{% for field in form.visible_fields %}
<div class="control-group {% if field.errors %}error{% endif %}">
<label class="control-label" for="{{ field.html_name }}">{{ field.label }}</label>
<div class="controls">
{{ field }}
{% if field.errors %}
<span class="help-inline">{{ field.errors }}</span>
{% endif %}
{% if field.help_text %}
<p class="help-block">{{ field.help_text }}</p>
{% endif %}
</div>
</div>
{% endfor %}

web/templates/submit.html
{% extends "base.html" %}

{% block content %}

<script type="text/javascript">
$(document).ready(function() {
    $('textarea').addClass('span6').wysihtml5();

    $('#preview_video').click(function() {
        var video_id = $('#id_video').val();
        var v_ids = video_id.split(" ");
        var video_preview_divs = "";
        for(var i = 0; i < v_ids.length; i++) {
            if ( /[A-Za-z0-9-_]{11}/.test(v_ids[i]) == true ) {
                video_preview_divs += '<div id="video_preview_div_' + v_ids[i] + '">Loading...</div><hr />';
            } else {
                video_preview_divs += '<div><p>' + v_ids[i] + ' is an invalid YouTube video id. It should be 11 characters long, and located in the url for your video. e.g. http://www.youtube.com/watch?v=VIDEO_ID</p></div><hr />';
            }
        }
        var params = { allowScriptAccess: "always" };
        var atts = { id: "modal_player", 'wmode': 'opaque' };
        $('body').append(
            '<div class="modal fade" id="preview_modal"><div class="modal-header">' +
            '<a class="close" data-dismiss="modal">x</a><h3>Video Preview</h3>' +
            '</div><div class="modal-body">' +
            video_preview_divs +
            '</div></div>'
        );
        for(var i = 0; i < v_ids.length; i++) {
            if ( /[A-Za-z0-9-_]{11}/.test(v_ids[i]) == true ) {
                swfobject.embedSWF("http://www.youtube.com/v/" + v_ids[i] + "?version=3&enablejsapi=1&playerapiid=player1", "video_preview_div_" + v_ids[i], "480", "295", "9", null, null, params, atts);
            }
        }
        $('#preview_modal').modal('show');
        $('#preview_modal').on('hidden', function () {
            $(this).remove();
        });
    });
});
</script>

<h2>Create New Submission</h2>

<form class="form-horizontal" action="{{ form_action }}" method="post">
{% csrf_token %}

{% include "form_template.html" with form=form %}

<div class="form-actions">
<input class="btn btn-primary" type="submit" value="Submit" />
<a class="btn" id="preview_video">Preview Video</a>
</div>
</form>

{% endblock %}